name: Examples

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # todo: add back ubuntu-latest, macos-latest
        os: [windows-latest]
        python-version: [3.9]
        example:
          - "examples/w60x-arduino-blink"
          - "examples/w60x-arduino-wifi-http-test"
          - "examples/w60x-sdk-blink"
          - "examples/w60x-sdk-button-input"
          - "examples/w60x-sdk-wifi-scan"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          platformio platform install file://.
      - name: Build examples
        run: |
          platformio run -d ${{ matrix.example }}
